# Projeto Python Game

**Entregáveis:**
1. Link do código fonte em seu repositório no GitHub;
1. Utilize pelo menos uma função em seu jogo;
1. Apresentação dia 04/12.

Construa um jogo utilizando os conceitos de programação aprendidos até o momento. Não precisa ser complicado: diversos jogos, como forca ou jogo da velha, são simples de se implementar. Simples ou complexo, um jogo em Python em geral contém um loop do jogo (muitas vezes um loop ```while True```) com as etapas abaixo:

1. Entrada do Usuário;
1. Atualização do estado do jogo;
1. Atualização das informações aos jogadores (via ```print``` por exemplo).

Além dos jogos acima, podemos utilizar jogos de azar (roleta por exemplo), cujas regras em geral são simples, ou então jogos da Antiguidade, como os descritos no site https://www.ancientgames.org/games/

In [53]:
import numpy as np

class Jogo_Velha:
    def __init__(self):
        self.tabuleiro = np.zeros((3,3), dtype=int)
        
    def check_ganhador(self):
        print(self.tabuleiro[0][0])
        
    def check_game_over(self):
        # retorna 1: game over
        # retorna 0: jogo não acabou
        if ((self.tabuleiro==0).sum())==0:
            return 1
        else:
            return 0

    def check_game_won(self):
        # retorna 1: jogador 1 venceu o jogo
        # retorna 2: jogador 2 venceu o jogo
        # retorna 0: jogo não acabou / ninguém venceu o jogo

        boolean_diagonal_1 = self.tabuleiro[0][0]==self.tabuleiro[1][1] and self.tabuleiro[1][1]==self.tabuleiro[2][2] and self.tabuleiro[2][2]!=0
        boolean_diagonal_2 = self.tabuleiro[0][2]==self.tabuleiro[1][1] and self.tabuleiro[1][1]==self.tabuleiro[2][0] and self.tabuleiro[2][0]!=0
        boolean_linha_1 = self.tabuleiro[0][0]==self.tabuleiro[0][1] and self.tabuleiro[0][1]==self.tabuleiro[0][2] and self.tabuleiro[0][2]!=0
        boolean_linha_2 = self.tabuleiro[1][0]==self.tabuleiro[1][1] and self.tabuleiro[1][1]==self.tabuleiro[1][2] and self.tabuleiro[1][2]!=0
        boolean_linha_3 = self.tabuleiro[2][0]==self.tabuleiro[2][1] and self.tabuleiro[2][1]==self.tabuleiro[2][2] and self.tabuleiro[2][2]!=0
        boolean_coluna_1 = self.tabuleiro[0][0]==self.tabuleiro[1][0] and self.tabuleiro[1][0]==self.tabuleiro[2][0] and self.tabuleiro[2][0]!=0
        boolean_coluna_2 = self.tabuleiro[0][1]==self.tabuleiro[1][1] and self.tabuleiro[1][1]==self.tabuleiro[2][1] and self.tabuleiro[2][1]!=0
        boolean_coluna_3 = self.tabuleiro[0][2]==self.tabuleiro[1][2] and self.tabuleiro[1][2]==self.tabuleiro[2][2] and self.tabuleiro[2][2]!=0

        
        if boolean_diagonal_1 or boolean_diagonal_2 or boolean_linha_1 or boolean_linha_2 or boolean_linha_3 or boolean_coluna_1 or boolean_coluna_2 or boolean_coluna_3:
            if boolean_diagonal_1:
                if self.tabuleiro[0][0]+self.tabuleiro[1][1]+self.tabuleiro[2][2]==3:
                    return 1
                else: return 2
            elif boolean_diagonal_2:
                if self.tabuleiro[0][2]+self.tabuleiro[1][1]+self.tabuleiro[2][0]==3:
                    return 1
                else: return 2
            elif boolean_linha_1:
                if self.tabuleiro[0][0]+self.tabuleiro[0][1]+self.tabuleiro[0][2]==3:
                    return 1
                else: return 2       
            elif boolean_linha_2:
                if self.tabuleiro[1][0]+self.tabuleiro[1][1]+self.tabuleiro[1][2]==3:
                    return 1
                else: return 2 
            elif boolean_linha_3:
                if self.tabuleiro[2][0]+self.tabuleiro[2][1]+self.tabuleiro[2][2]==3:
                    return 1
                else: return 2                
            elif boolean_coluna_1:
                if self.tabuleiro[0][0]+self.tabuleiro[1][0]+self.tabuleiro[2][0]==3:
                    return 1
                else: return 2                
            elif boolean_coluna_2:
                if self.tabuleiro[0][1]+self.tabuleiro[1][1]+self.tabuleiro[2][1]==3:
                    return 1
                else: return 2                
            elif boolean_coluna_3:
                if self.tabuleiro[0][2]+self.tabuleiro[1][2]+self.tabuleiro[2][2]==3:
                    return 1
                else: return 2 
        else: return 0

jogo1 = Jogo_Velha()      
i = False

while(jogo1.check_game_over()==0 and jogo1.check_game_won()==0):
    print('Jogador',(i+1))
    posicao = input('Digite posição da jogada:')
    jogo1.tabuleiro[int(posicao[1])][int(posicao[3])] = int(i)+1
    print(jogo1.tabuleiro)
    i = not i
    print('\n=========\n')
    
if(jogo1.check_game_won()!=0):
    print('jogador vencedor:', jogo1.check_game_won())

Jogador 1
Digite posição da jogada:(0,0)
[[1 0 0]
 [0 0 0]
 [0 0 0]]


Jogador 2
Digite posição da jogada:(0,1)
[[1 2 0]
 [0 0 0]
 [0 0 0]]


Jogador 1
Digite posição da jogada:(0,2)
[[1 2 1]
 [0 0 0]
 [0 0 0]]


Jogador 2
Digite posição da jogada:(1,0)
[[1 2 1]
 [2 0 0]
 [0 0 0]]


Jogador 1
Digite posição da jogada:(1,1)
[[1 2 1]
 [2 1 0]
 [0 0 0]]


Jogador 2
Digite posição da jogada:(1,2)
[[1 2 1]
 [2 1 2]
 [0 0 0]]


Jogador 1
Digite posição da jogada:(2,0)
[[1 2 1]
 [2 1 2]
 [1 0 0]]


jogador vencedor: 1


In [ ]:
# perguntar em separado linhas e colunas e arrumar índice
# função customizada de print (x, o e vazio)
# checar erro se jogar na mesma posição
# erro se entrada for string
# fazer o PC jogar