In [1]:
import numpy as np

minha_lista = [1,2,3,4]
meu_array = np.array(minha_lista)
print(meu_array)
print(minha_lista)

[1 2 3 4]
[1, 2, 3, 4]


In [3]:
meu_array_aleatorio = np.random.random(size=10)
print(meu_array_aleatorio)

[0.79273656 0.93596047 0.56945981 0.43498199 0.84655103 0.29565587
 0.86390537 0.73091019 0.17397136 0.17207524]


In [7]:
np.array([1,2,3,'4'],dtype=int)

array([1, 2, 3, 4])

In [8]:
np.array([1,2,3,'4'])

array(['1', '2', '3', '4'], dtype='<U11')

In [9]:
np.array([1,2,3,'4'],dtype=str)

array(['1', '2', '3', '4'], dtype='<U1')

In [10]:
array_dez = np.full((10,), fill_value = 10)
array_dez

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

In [12]:
m_10_5 = np.zeros((10,5))
m_10_5

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
print(m_10_5.shape)
print(m_10_5.size)

(10, 5)
50


In [14]:
m_3_3 = np.random.random(size=(3,3))
m_3_3

array([[0.77277424, 0.16724252, 0.0301677 ],
       [0.56903145, 0.68440187, 0.01218691],
       [0.48443981, 0.77122398, 0.89308741]])

In [15]:
m_3_3.ravel()[3]

0.5690314531901972